FROM golang:1.20-alpine

WORKDIR /app

COPY . .

RUN go get
# RUN go mod download
# RUN go mod tidy

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/bin-app /app/main.go

EXPOSE 8090

CMD ["/app/bin-app"]
